# Generated by Django 3.1.3 on 2020-11-30 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0004_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='recieve',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='send',
        ),
        migrations.AddField(
            model_name='friends',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friends',
            name='status',
            field=models.CharField(choices=[('Requested', 'requested'), ('Confirmed', 'confirmed'), ('Ignore', 'Ignore')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='friendrequest',
        ),
    ]
